import '@router/directives/data-router'
import '@router/directives/data-router-cloak'
import '@router/directives/data-router-link'
import '@router/directives/data-router-link-active'
import '@router/directives/data-router-page'
import '@router/directives/data-router-title'
